# Pandas

In [2]:
import pandas as pd
data = [1, 2, 3, 4, 5, 5, 6]
series = pd.Series(data)
print("Series:\n", series)

Series:
 0    1
1    2
2    3
3    4
4    5
5    5
6    6
dtype: int64

In [4]:
print(type(series))

<class 'pandas.core.series.Series'>

In [5]:
data = {'a' : 1, 'b' : 2, 'c' : 3, 'd' : 4}
s = pd.Series(data)
print(s)

a    1
b    2
c    3
d    4
dtype: int64

In [7]:
data = [10, 20, 30]
index = ['a', 'b', 'c']
series = pd.Series(data, index)
print(series)

a    10
b    20
c    30
dtype: int64

In [8]:
data = {'Name' : ['Krish', 'John', 'Jack'],
        'Age' : [25, 40, 35],
        'city' : ['Banglore', 'UP', 'MP']
}
df = pd.DataFrame(data)
print(df)

    Name  Age      city
0  Krish   25  Banglore
1   John   40        UP
2   Jack   35        MP

In [12]:
data = [
    {'name' : 'Krish', 'age' : 32, 'city' : 'Banglore'},
    {'name' : 'John', 'age' : 34, 'city' : 'Banglore'},
    {'name' : 'Bappy', 'age' : 30, 'city' : 'Banglore'},
    {'name' : 'Jack', 'age' : 29, 'city' : 'Haryana'}
]
df = pd.DataFrame(data)
print(df)

    name  age      city
0  Krish   32  Banglore
1   John   34  Banglore
2  Bappy   30  Banglore
3   Jack   29   Haryana

In [13]:
df

    name  age      city
0  Krish   32  Banglore
1   John   34  Banglore
2  Bappy   30  Banglore
3   Jack   29   Haryana

In [7]:
df = pd.read_csv('sales_data.csv')
df.head(5)

         Date     Product Region  Units_Sold  Unit_Price  Total_Sale
0  2024-02-08      Laptop  South          24         884       21216
1  2024-01-29      Laptop   East          33         203        6699
2  2024-01-15  Headphones  North          24         492       11808
3  2024-02-12      Tablet   West          11         910       10010
4  2024-01-08      Tablet  North          49         345       16905

In [8]:
df.tail(5)

          Date     Product Region  Units_Sold  Unit_Price  Total_Sale
95  2024-01-15      Tablet   East           2         195         390
96  2024-02-14      Laptop   West          27         737       19899
97  2024-01-01       Phone   West          42         217        9114
98  2024-01-25       Phone   East           2         659        1318
99  2024-01-07  Headphones   West          26         700       18200

In [9]:
## accesing data from data frame
data

[{'name': 'Krish', 'age': 32, 'city': 'Banglore'},
 {'name': 'John', 'age': 34, 'city': 'Banglore'},
 {'name': 'Bappy', 'age': 30, 'city': 'Banglore'},
 {'name': 'Jack', 'age': 29, 'city': 'Haryana'}]

In [10]:
df

          Date     Product Region  Units_Sold  Unit_Price  Total_Sale
0   2024-02-08      Laptop  South          24         884       21216
1   2024-01-29      Laptop   East          33         203        6699
2   2024-01-15  Headphones  North          24         492       11808
3   2024-02-12      Tablet   West          11         910       10010
4   2024-01-08      Tablet  North          49         345       16905
..         ...         ...    ...         ...         ...         ...
95  2024-01-15      Tablet   East           2         195         390
96  2024-02-14      Laptop   West          27         737       19899
97  2024-01-01       Phone   West          42         217        9114
98  2024-01-25       Phone   East           2         659        1318
99  2024-01-07  Headphones   West          26         700       18200

[100 rows x 6 columns]

In [14]:
df['name']

0    Krish
1     John
2    Bappy
3     Jack
Name: name, dtype: object

In [18]:
type(df['name'])

pandas.core.series.Series

In [20]:
df.loc[0]

name       Krish
age           32
city    Banglore
Name: 0, dtype: object

In [21]:
df.iloc[0]

name       Krish
age           32
city    Banglore
Name: 0, dtype: object

In [22]:
df.loc[0][0]

/var/folders/_k/yx6vfd_n1j1c7qlmys3r5tmm0000gn/T/ipykernel_12490/2527876973.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.loc[0][0]

'Krish'

In [23]:
## accesing a specified elment
df['name']

0    Krish
1     John
2    Bappy
3     Jack
Name: name, dtype: object

In [24]:
df

    name  age      city
0  Krish   32  Banglore
1   John   34  Banglore
2  Bappy   30  Banglore
3   Jack   29   Haryana

In [27]:
print(df.at[1, 'age'])

34

In [28]:
df

    name  age      city
0  Krish   32  Banglore
1   John   34  Banglore
2  Bappy   30  Banglore
3   Jack   29   Haryana

In [29]:
print(df.at[2, 'age'])

30

In [30]:
print(df.at[1, 'name'])

John

In [31]:
## Accesing a specified elemnt using iat
df.iat[2, 2]

'Banglore'

In [32]:
df

    name  age      city
0  Krish   32  Banglore
1   John   34  Banglore
2  Bappy   30  Banglore
3   Jack   29   Haryana

In [33]:
## Data minpulation with dataframe
df

    name  age      city
0  Krish   32  Banglore
1   John   34  Banglore
2  Bappy   30  Banglore
3   Jack   29   Haryana

In [34]:
df['salary'] = [50, 60, 70, 80]

In [35]:
df

    name  age      city  salary
0  Krish   32  Banglore      50
1   John   34  Banglore      60
2  Bappy   30  Banglore      70
3   Jack   29   Haryana      80

In [ ]:
## Remove a column
df.drop('salary')

KeyError: "['salary'] not found in axis"

In [37]:
df.drop('salary', axis = 1)

    name  age      city
0  Krish   32  Banglore
1   John   34  Banglore
2  Bappy   30  Banglore
3   Jack   29   Haryana

In [38]:
df

    name  age      city  salary
0  Krish   32  Banglore      50
1   John   34  Banglore      60
2  Bappy   30  Banglore      70
3   Jack   29   Haryana      80

In [39]:
df.drop('salary', axis = 1, inplace = True)

In [40]:
df

    name  age      city
0  Krish   32  Banglore
1   John   34  Banglore
2  Bappy   30  Banglore
3   Jack   29   Haryana

In [41]:
df['age'] = df['age'] + 1

In [42]:
df

    name  age      city
0  Krish   33  Banglore
1   John   35  Banglore
2  Bappy   31  Banglore
3   Jack   30   Haryana

In [43]:
df.drop(0)

    name  age      city
1   John   35  Banglore
2  Bappy   31  Banglore
3   Jack   30   Haryana

In [44]:
df

    name  age      city
0  Krish   33  Banglore
1   John   35  Banglore
2  Bappy   31  Banglore
3   Jack   30   Haryana

In [45]:
df.drop(0, inplace = True)

In [46]:
df

    name  age      city
1   John   35  Banglore
2  Bappy   31  Banglore
3   Jack   30   Haryana

In [47]:
df = pd.read_csv('sales_data.csv')
df.head(5)

         Date     Product Region  Units_Sold  Unit_Price  Total_Sale
0  2024-02-08      Laptop  South          24         884       21216
1  2024-01-29      Laptop   East          33         203        6699
2  2024-01-15  Headphones  North          24         492       11808
3  2024-02-12      Tablet   West          11         910       10010
4  2024-01-08      Tablet  North          49         345       16905

In [50]:
print('DataType\n', df.dtypes)
print('Statical Summery\n', df.describe())

DataType
 Date          object
Product       object
Region        object
Units_Sold     int64
Unit_Price     int64
Total_Sale     int64
dtype: object
Statical Summery
        Units_Sold  Unit_Price    Total_Sale
count  100.000000  100.000000    100.000000
mean    28.060000  592.490000  16556.040000
std     13.363466  281.741571  11861.900766
min      2.000000  104.000000    390.000000
25%     20.000000  332.500000   6206.000000
50%     29.500000  664.000000  16334.000000
75%     37.250000  852.000000  22603.250000
max     49.000000  983.000000  46368.000000

In [2]:
df = pd.read_csv('sales_data.csv')

In [3]:
## fetch data from file
df.head(5)

         Date     Product Region  Units_Sold  Unit_Price  Total_Sale
0  2024-02-08      Laptop  South          24         884       21216
1  2024-01-29      Laptop   East          33         203        6699
2  2024-01-15  Headphones  North          24         492       11808
3  2024-02-12      Tablet   West          11         910       10010
4  2024-01-08      Tablet  North          49         345       16905

In [4]:
df.tail(5)

          Date     Product Region  Units_Sold  Unit_Price  Total_Sale
95  2024-01-15      Tablet   East           2         195         390
96  2024-02-14      Laptop   West          27         737       19899
97  2024-01-01       Phone   West          42         217        9114
98  2024-01-25       Phone   East           2         659        1318
99  2024-01-07  Headphones   West          26         700       18200

In [6]:
df.describe()

       Units_Sold  Unit_Price    Total_Sale
count  100.000000  100.000000    100.000000
mean    28.060000  592.490000  16556.040000
std     13.363466  281.741571  11861.900766
min      2.000000  104.000000    390.000000
25%     20.000000  332.500000   6206.000000
50%     29.500000  664.000000  16334.000000
75%     37.250000  852.000000  22603.250000
max     49.000000  983.000000  46368.000000

In [7]:
df.dtypes

Date          object
Product       object
Region        object
Units_Sold     int64
Unit_Price     int64
Total_Sale     int64
dtype: object

In [9]:
## Handling msiing values
df.isnull()

     Date  Product  Region  Units_Sold  Unit_Price  Total_Sale
0   False    False   False       False       False       False
1   False    False   False       False       False       False
2   False    False   False       False       False       False
3   False    False   False       False       False       False
4   False    False   False       False       False       False
..    ...      ...     ...         ...         ...         ...
95  False    False   False       False       False       False
96  False    False   False       False       False       False
97  False    False   False       False       False       False
98  False    False   False       False       False       False
99  False    False   False       False       False       False

[100 rows x 6 columns]

In [12]:
df.isnull

<bound method DataFrame.isnull of           Date     Product Region  Units_Sold  Unit_Price  Total_Sale
0   2024-02-08      Laptop  South          24         884       21216
1   2024-01-29      Laptop   East          33         203        6699
2   2024-01-15  Headphones  North          24         492       11808
3   2024-02-12      Tablet   West          11         910       10010
4   2024-01-08      Tablet  North          49         345       16905
..         ...         ...    ...         ...         ...         ...
95  2024-01-15      Tablet   East           2         195         390
96  2024-02-14      Laptop   West          27         737       19899
97  2024-01-01       Phone   West          42         217        9114
98  2024-01-25       Phone   East           2         659        1318
99  2024-01-07  Headphones   West          26         700       18200

[100 rows x 6 columns]>

In [14]:
df.isnull().any(axis = 1)

0     False
1     False
2     False
3     False
4     False
      ...
95    False
96    False
97    False
98    False
99    False
Length: 100, dtype: bool

In [15]:
df.isnull().any()

Date          False
Product       False
Region        False
Units_Sold    False
Unit_Price    False
Total_Sale    False
dtype: bool

In [16]:
df.isnull().sum()

Date          0
Product       0
Region        0
Units_Sold    0
Unit_Price    0
Total_Sale    0
dtype: int64

In [17]:
df.fillna(0)

          Date     Product Region  Units_Sold  Unit_Price  Total_Sale
0   2024-02-08      Laptop  South          24         884       21216
1   2024-01-29      Laptop   East          33         203        6699
2   2024-01-15  Headphones  North          24         492       11808
3   2024-02-12      Tablet   West          11         910       10010
4   2024-01-08      Tablet  North          49         345       16905
..         ...         ...    ...         ...         ...         ...
95  2024-01-15      Tablet   East           2         195         390
96  2024-02-14      Laptop   West          27         737       19899
97  2024-01-01       Phone   West          42         217        9114
98  2024-01-25       Phone   East           2         659        1318
99  2024-01-07  Headphones   West          26         700       18200

[100 rows x 6 columns]

In [18]:
df_filled = df.fillna(0)

In [19]:
df_filled

          Date     Product Region  Units_Sold  Unit_Price  Total_Sale
0   2024-02-08      Laptop  South          24         884       21216
1   2024-01-29      Laptop   East          33         203        6699
2   2024-01-15  Headphones  North          24         492       11808
3   2024-02-12      Tablet   West          11         910       10010
4   2024-01-08      Tablet  North          49         345       16905
..         ...         ...    ...         ...         ...         ...
95  2024-01-15      Tablet   East           2         195         390
96  2024-02-14      Laptop   West          27         737       19899
97  2024-01-01       Phone   West          42         217        9114
98  2024-01-25       Phone   East           2         659        1318
99  2024-01-07  Headphones   West          26         700       18200

[100 rows x 6 columns]

In [20]:
import pandas as pd

In [21]:
df = pd.read_csv('data.csv')

In [22]:
df

          Date     Category  Value     Product     Sales Region
0   2023-09-01     Clothing  343.0      Jacket  41873.29  North
1   2023-04-26        Books  378.0  Headphones  24518.15   East
2          NaN  Electronics  740.0      Jacket  44212.64  South
3          NaN         Food  469.0       Pizza   7143.52  North
4          NaN     Clothing  546.0       Pizza  32402.12  South
5   2023-07-21         Food  656.0      Comics  11540.52    NaN
6   2023-12-26          NaN  574.0       Novel  48954.12   East
7          NaN         Food  335.0  Headphones  30537.96   West
8   2023-11-05  Electronics    NaN      Jacket   7544.20   West
9   2023-10-15     Clothing  625.0  Headphones  19003.08   West
10  2023-06-13        Books  146.0      Laptop  24057.56   West
11  2023-07-08     Clothing  625.0      Comics  24977.10   East
12  2023-08-20        Books   11.0      Laptop  33908.63  South
13  2023-05-17        Books  798.0      Comics   8653.25   West
14  2023-02-26  Electronics  809.0      Laptop   2537.99  South
15  2023-06-23          NaN  514.0      Burger       NaN   East
16  2023-02-08        Books  257.0       Pizza  35214.31   East
17  2023-01-17     Clothing    NaN       Pizza  34658.40   East
18  2023-04-06     Clothing  448.0  Headphones  40719.60   East
19  2023-07-19  Electronics  331.0      Burger  21930.95   West
20  2023-10-27  Electronics   67.0  Headphones  19308.52  North
21  2023-06-26         Food  688.0      Laptop  26193.67   West
22  2024-01-01         Food  964.0  Headphones   7263.47    NaN
23  2023-03-09  Electronics  790.0      Comics       NaN    NaN
24  2023-09-17        Books  590.0      Burger  42581.00   West
25  2023-03-06         Food  545.0         NaN  33593.48   West
26  2023-06-12     Clothing  630.0      Laptop  20538.23  North
27         NaN  Electronics    NaN      Jacket  16749.29   East
28  2023-09-04  Electronics  316.0      Burger  33721.90   East
29  2023-07-13          NaN  440.0      Comics  14711.25  South
30  2023-11-11        Books  418.0      Comics  13729.77    NaN
31  2023-08-14  Electronics  296.0       Shirt  43750.99  South
32  2023-06-25     Clothing  317.0       Novel  16576.52  South
33  2023-11-05  Electronics  215.0  Headphones  35668.37   West
34  2023-07-01  Electronics   77.0      Comics   2669.40   West
35  2023-12-03         Food  927.0       Shirt  45094.88   West
36  2023-12-24     Clothing  669.0      Laptop  32936.17  North
37  2023-09-27          NaN   21.0      Burger  11273.22  South
38  2023-03-30        Books    NaN         NaN  11235.74  South
39  2023-09-22        Books  275.0      Burger  44395.79   East
40  2023-03-09  Electronics  683.0  Headphones   7519.55  South
41  2023-09-06     Clothing  370.0      Jacket  25715.33   West
42  2023-04-11  Electronics   49.0      Burger  31805.53   East
43  2023-06-14        Books  152.0      Laptop  30042.08  South
44  2023-04-11  Electronics  411.0      Laptop  10966.47   East
45  2023-01-14  Electronics    NaN       Novel       NaN  North
46  2023-11-24     Clothing  322.0       Novel  13885.47   East
47  2023-02-15        Books  131.0       Novel  35548.42  North
48  2023-01-28         Food  322.0         NaN       NaN  North
49  2023-04-16          NaN  179.0      Comics       NaN  North

In [23]:
df.head(5)

         Date     Category  Value     Product     Sales Region
0  2023-09-01     Clothing  343.0      Jacket  41873.29  North
1  2023-04-26        Books  378.0  Headphones  24518.15   East
2         NaN  Electronics  740.0      Jacket  44212.64  South
3         NaN         Food  469.0       Pizza   7143.52  North
4         NaN     Clothing  546.0       Pizza  32402.12  South

In [24]:
df.tail(5)

          Date     Category  Value Product     Sales Region
45  2023-01-14  Electronics    NaN   Novel       NaN  North
46  2023-11-24     Clothing  322.0   Novel  13885.47   East
47  2023-02-15        Books  131.0   Novel  35548.42  North
48  2023-01-28         Food  322.0     NaN       NaN  North
49  2023-04-16          NaN  179.0  Comics       NaN  North

In [25]:
## Fetch the data from file
df.describe()

            Value         Sales
count   45.000000     45.000000
mean   432.644444  24930.264444
std    249.025752  13188.885760
min     11.000000   2537.990000
25%    275.000000  13729.770000
50%    411.000000  24977.100000
75%    625.000000  34658.400000
max    964.000000  48954.120000

In [27]:
df.dtypes

Date         object
Category     object
Value       float64
Product      object
Sales       float64
Region       object
dtype: object

In [31]:
## Handiling missing values
df.isnull()

     Date  Category  Value  Product  Sales  Region
0   False     False  False    False  False   False
1   False     False  False    False  False   False
2    True     False  False    False  False   False
3    True     False  False    False  False   False
4    True     False  False    False  False   False
5   False     False  False    False  False    True
6   False      True  False    False  False   False
7    True     False  False    False  False   False
8   False     False   True    False  False   False
9   False     False  False    False  False   False
10  False     False  False    False  False   False
11  False     False  False    False  False   False
12  False     False  False    False  False   False
13  False     False  False    False  False   False
14  False     False  False    False  False   False
15  False      True  False    False   True   False
16  False     False  False    False  False   False
17  False     False   True    False  False   False
18  False     False  False    False  False   False
19  False     False  False    False  False   False
20  False     False  False    False  False   False
21  False     False  False    False  False   False
22  False     False  False    False  False    True
23  False     False  False    False   True    True
24  False     False  False    False  False   False
25  False     False  False     True  False   False
26  False     False  False    False  False   False
27   True     False   True    False  False   False
28  False     False  False    False  False   False
29  False      True  False    False  False   False
30  False     False  False    False  False    True
31  False     False  False    False  False   False
32  False     False  False    False  False   False
33  False     False  False    False  False   False
34  False     False  False    False  False   False
35  False     False  False    False  False   False
36  False     False  False    False  False   False
37  False      True  False    False  False   False
38  False     False   True     True  False   False
39  False     False  False    False  False   False
40  False     False  False    False  False   False
41  False     False  False    False  False   False
42  False     False  False    False  False   False
43  False     False  False    False  False   False
44  False     False  False    False  False   False
45  False     False   True    False   True   False
46  False     False  False    False  False   False
47  False     False  False    False  False   False
48  False     False  False     True   True   False
49  False      True  False    False   True   False

In [32]:
df.isnull().any(axis = 1)

0     False
1     False
2      True
3      True
4      True
5      True
6      True
7      True
8      True
9     False
10    False
11    False
12    False
13    False
14    False
15     True
16    False
17     True
18    False
19    False
20    False
21    False
22     True
23     True
24    False
25     True
26    False
27     True
28    False
29     True
30     True
31    False
32    False
33    False
34    False
35    False
36    False
37     True
38     True
39    False
40    False
41    False
42    False
43    False
44    False
45     True
46    False
47    False
48     True
49     True
dtype: bool

In [33]:
df.isnull().any()

Date        True
Category    True
Value       True
Product     True
Sales       True
Region      True
dtype: bool

In [34]:
df.isnull().sum()

Date        5
Category    5
Value       5
Product     3
Sales       5
Region      4
dtype: int64

In [38]:
df_filled = df.fillna(0)

In [36]:
df_filled.head(6)

         Date     Product Region  Units_Sold  Unit_Price  Total_Sale
0  2024-02-08      Laptop  South          24         884       21216
1  2024-01-29      Laptop   East          33         203        6699
2  2024-01-15  Headphones  North          24         492       11808
3  2024-02-12      Tablet   West          11         910       10010
4  2024-01-08      Tablet  North          49         345       16905
5  2024-01-21      Laptop  North           8         275        2200

In [40]:
df_filled

          Date     Category  Value     Product     Sales Region
0   2023-09-01     Clothing  343.0      Jacket  41873.29  North
1   2023-04-26        Books  378.0  Headphones  24518.15   East
2            0  Electronics  740.0      Jacket  44212.64  South
3            0         Food  469.0       Pizza   7143.52  North
4            0     Clothing  546.0       Pizza  32402.12  South
5   2023-07-21         Food  656.0      Comics  11540.52      0
6   2023-12-26            0  574.0       Novel  48954.12   East
7            0         Food  335.0  Headphones  30537.96   West
8   2023-11-05  Electronics    0.0      Jacket   7544.20   West
9   2023-10-15     Clothing  625.0  Headphones  19003.08   West
10  2023-06-13        Books  146.0      Laptop  24057.56   West
11  2023-07-08     Clothing  625.0      Comics  24977.10   East
12  2023-08-20        Books   11.0      Laptop  33908.63  South
13  2023-05-17        Books  798.0      Comics   8653.25   West
14  2023-02-26  Electronics  809.0      Laptop   2537.99  South
15  2023-06-23            0  514.0      Burger      0.00   East
16  2023-02-08        Books  257.0       Pizza  35214.31   East
17  2023-01-17     Clothing    0.0       Pizza  34658.40   East
18  2023-04-06     Clothing  448.0  Headphones  40719.60   East
19  2023-07-19  Electronics  331.0      Burger  21930.95   West
20  2023-10-27  Electronics   67.0  Headphones  19308.52  North
21  2023-06-26         Food  688.0      Laptop  26193.67   West
22  2024-01-01         Food  964.0  Headphones   7263.47      0
23  2023-03-09  Electronics  790.0      Comics      0.00      0
24  2023-09-17        Books  590.0      Burger  42581.00   West
25  2023-03-06         Food  545.0           0  33593.48   West
26  2023-06-12     Clothing  630.0      Laptop  20538.23  North
27           0  Electronics    0.0      Jacket  16749.29   East
28  2023-09-04  Electronics  316.0      Burger  33721.90   East
29  2023-07-13            0  440.0      Comics  14711.25  South
30  2023-11-11        Books  418.0      Comics  13729.77      0
31  2023-08-14  Electronics  296.0       Shirt  43750.99  South
32  2023-06-25     Clothing  317.0       Novel  16576.52  South
33  2023-11-05  Electronics  215.0  Headphones  35668.37   West
34  2023-07-01  Electronics   77.0      Comics   2669.40   West
35  2023-12-03         Food  927.0       Shirt  45094.88   West
36  2023-12-24     Clothing  669.0      Laptop  32936.17  North
37  2023-09-27            0   21.0      Burger  11273.22  South
38  2023-03-30        Books    0.0           0  11235.74  South
39  2023-09-22        Books  275.0      Burger  44395.79   East
40  2023-03-09  Electronics  683.0  Headphones   7519.55  South
41  2023-09-06     Clothing  370.0      Jacket  25715.33   West
42  2023-04-11  Electronics   49.0      Burger  31805.53   East
43  2023-06-14        Books  152.0      Laptop  30042.08  South
44  2023-04-11  Electronics  411.0      Laptop  10966.47   East
45  2023-01-14  Electronics    0.0       Novel      0.00  North
46  2023-11-24     Clothing  322.0       Novel  13885.47   East
47  2023-02-15        Books  131.0       Novel  35548.42  North
48  2023-01-28         Food  322.0           0      0.00  North
49  2023-04-16            0  179.0      Comics      0.00  North

In [41]:
df

          Date     Category  Value     Product     Sales Region
0   2023-09-01     Clothing  343.0      Jacket  41873.29  North
1   2023-04-26        Books  378.0  Headphones  24518.15   East
2          NaN  Electronics  740.0      Jacket  44212.64  South
3          NaN         Food  469.0       Pizza   7143.52  North
4          NaN     Clothing  546.0       Pizza  32402.12  South
5   2023-07-21         Food  656.0      Comics  11540.52    NaN
6   2023-12-26          NaN  574.0       Novel  48954.12   East
7          NaN         Food  335.0  Headphones  30537.96   West
8   2023-11-05  Electronics    NaN      Jacket   7544.20   West
9   2023-10-15     Clothing  625.0  Headphones  19003.08   West
10  2023-06-13        Books  146.0      Laptop  24057.56   West
11  2023-07-08     Clothing  625.0      Comics  24977.10   East
12  2023-08-20        Books   11.0      Laptop  33908.63  South
13  2023-05-17        Books  798.0      Comics   8653.25   West
14  2023-02-26  Electronics  809.0      Laptop   2537.99  South
15  2023-06-23          NaN  514.0      Burger       NaN   East
16  2023-02-08        Books  257.0       Pizza  35214.31   East
17  2023-01-17     Clothing    NaN       Pizza  34658.40   East
18  2023-04-06     Clothing  448.0  Headphones  40719.60   East
19  2023-07-19  Electronics  331.0      Burger  21930.95   West
20  2023-10-27  Electronics   67.0  Headphones  19308.52  North
21  2023-06-26         Food  688.0      Laptop  26193.67   West
22  2024-01-01         Food  964.0  Headphones   7263.47    NaN
23  2023-03-09  Electronics  790.0      Comics       NaN    NaN
24  2023-09-17        Books  590.0      Burger  42581.00   West
25  2023-03-06         Food  545.0         NaN  33593.48   West
26  2023-06-12     Clothing  630.0      Laptop  20538.23  North
27         NaN  Electronics    NaN      Jacket  16749.29   East
28  2023-09-04  Electronics  316.0      Burger  33721.90   East
29  2023-07-13          NaN  440.0      Comics  14711.25  South
30  2023-11-11        Books  418.0      Comics  13729.77    NaN
31  2023-08-14  Electronics  296.0       Shirt  43750.99  South
32  2023-06-25     Clothing  317.0       Novel  16576.52  South
33  2023-11-05  Electronics  215.0  Headphones  35668.37   West
34  2023-07-01  Electronics   77.0      Comics   2669.40   West
35  2023-12-03         Food  927.0       Shirt  45094.88   West
36  2023-12-24     Clothing  669.0      Laptop  32936.17  North
37  2023-09-27          NaN   21.0      Burger  11273.22  South
38  2023-03-30        Books    NaN         NaN  11235.74  South
39  2023-09-22        Books  275.0      Burger  44395.79   East
40  2023-03-09  Electronics  683.0  Headphones   7519.55  South
41  2023-09-06     Clothing  370.0      Jacket  25715.33   West
42  2023-04-11  Electronics   49.0      Burger  31805.53   East
43  2023-06-14        Books  152.0      Laptop  30042.08  South
44  2023-04-11  Electronics  411.0      Laptop  10966.47   East
45  2023-01-14  Electronics    NaN       Novel       NaN  North
46  2023-11-24     Clothing  322.0       Novel  13885.47   East
47  2023-02-15        Books  131.0       Novel  35548.42  North
48  2023-01-28         Food  322.0         NaN       NaN  North
49  2023-04-16          NaN  179.0      Comics       NaN  North

In [44]:
df.isnull().any()

Date        True
Category    True
Value       True
Product     True
Sales       True
Region      True
dtype: bool

In [45]:
df['Sales_fillNA'] = df['Sales'].fillna(df['Sales'].mean())
df

          Date     Category  Value     Product     Sales Region  Sales_fillNA
0   2023-09-01     Clothing  343.0      Jacket  41873.29  North  41873.290000
1   2023-04-26        Books  378.0  Headphones  24518.15   East  24518.150000
2          NaN  Electronics  740.0      Jacket  44212.64  South  44212.640000
3          NaN         Food  469.0       Pizza   7143.52  North   7143.520000
4          NaN     Clothing  546.0       Pizza  32402.12  South  32402.120000
5   2023-07-21         Food  656.0      Comics  11540.52    NaN  11540.520000
6   2023-12-26          NaN  574.0       Novel  48954.12   East  48954.120000
7          NaN         Food  335.0  Headphones  30537.96   West  30537.960000
8   2023-11-05  Electronics    NaN      Jacket   7544.20   West   7544.200000
9   2023-10-15     Clothing  625.0  Headphones  19003.08   West  19003.080000
10  2023-06-13        Books  146.0      Laptop  24057.56   West  24057.560000
11  2023-07-08     Clothing  625.0      Comics  24977.10   East  24977.100000
12  2023-08-20        Books   11.0      Laptop  33908.63  South  33908.630000
13  2023-05-17        Books  798.0      Comics   8653.25   West   8653.250000
14  2023-02-26  Electronics  809.0      Laptop   2537.99  South   2537.990000
15  2023-06-23          NaN  514.0      Burger       NaN   East  24930.264444
16  2023-02-08        Books  257.0       Pizza  35214.31   East  35214.310000
17  2023-01-17     Clothing    NaN       Pizza  34658.40   East  34658.400000
18  2023-04-06     Clothing  448.0  Headphones  40719.60   East  40719.600000
19  2023-07-19  Electronics  331.0      Burger  21930.95   West  21930.950000
20  2023-10-27  Electronics   67.0  Headphones  19308.52  North  19308.520000
21  2023-06-26         Food  688.0      Laptop  26193.67   West  26193.670000
22  2024-01-01         Food  964.0  Headphones   7263.47    NaN   7263.470000
23  2023-03-09  Electronics  790.0      Comics       NaN    NaN  24930.264444
24  2023-09-17        Books  590.0      Burger  42581.00   West  42581.000000
25  2023-03-06         Food  545.0         NaN  33593.48   West  33593.480000
26  2023-06-12     Clothing  630.0      Laptop  20538.23  North  20538.230000
27         NaN  Electronics    NaN      Jacket  16749.29   East  16749.290000
28  2023-09-04  Electronics  316.0      Burger  33721.90   East  33721.900000
29  2023-07-13          NaN  440.0      Comics  14711.25  South  14711.250000
30  2023-11-11        Books  418.0      Comics  13729.77    NaN  13729.770000
31  2023-08-14  Electronics  296.0       Shirt  43750.99  South  43750.990000
32  2023-06-25     Clothing  317.0       Novel  16576.52  South  16576.520000
33  2023-11-05  Electronics  215.0  Headphones  35668.37   West  35668.370000
34  2023-07-01  Electronics   77.0      Comics   2669.40   West   2669.400000
35  2023-12-03         Food  927.0       Shirt  45094.88   West  45094.880000
36  2023-12-24     Clothing  669.0      Laptop  32936.17  North  32936.170000
37  2023-09-27          NaN   21.0      Burger  11273.22  South  11273.220000
38  2023-03-30        Books    NaN         NaN  11235.74  South  11235.740000
39  2023-09-22        Books  275.0      Burger  44395.79   East  44395.790000
40  2023-03-09  Electronics  683.0  Headphones   7519.55  South   7519.550000
41  2023-09-06     Clothing  370.0      Jacket  25715.33   West  25715.330000
42  2023-04-11  Electronics   49.0      Burger  31805.53   East  31805.530000
43  2023-06-14        Books  152.0      Laptop  30042.08  South  30042.080000
44  2023-04-11  Electronics  411.0      Laptop  10966.47   East  10966.470000
45  2023-01-14  Electronics    NaN       Novel       NaN  North  24930.264444
46  2023-11-24     Clothing  322.0       Novel  13885.47   East  13885.470000
47  2023-02-15        Books  131.0       Novel  35548.42  North  35548.420000
48  2023-01-28         Food  322.0         NaN       NaN  North  24930.264444
49  2023-04-16          NaN  179.0      Comics       NaN  North  24930.264444

In [49]:
df.dtypes

Date             object
Category         object
Value           float64
Product          object
Sales           float64
Region           object
Sales_fillNA    float64
dtype: object

In [53]:
## Renaming Column
df = df.rename(columns={'Date' :  'Sales _date'})
df.head(5)

  Sales _date     Category  Value     Product     Sales Region  Sales_fillNA
0  2023-09-01     Clothing  343.0      Jacket  41873.29  North      41873.29
1  2023-04-26        Books  378.0  Headphones  24518.15   East      24518.15
2         NaN  Electronics  740.0      Jacket  44212.64  South      44212.64
3         NaN         Food  469.0       Pizza   7143.52  North       7143.52
4         NaN     Clothing  546.0       Pizza  32402.12  South      32402.12

In [58]:
## Change DataType
df['New_Value'] = df['Value'].fillna(df['Value'].mean()).astype(int)
df.head()

,Sales _date,Category,Value,Product,Sales,Region,Sales_fillNA,New_Value
0,2023-09-01,Clothing,343.0,Jacket,41873.29,North,41873.29,343
1,2023-04-26,Books,378.0,Headphones,24518.15,East,24518.15,378
2,NaN,Electronics,740.0,Jacket,44212.64,South,44212.64,740
3,NaN,Food,469.0,Pizza,7143.52,North,7143.52,469
4,NaN,Clothing,546.0,Pizza,32402.12,South,32402.12,546

In [59]:
df['Value_New'] = df['Value'].apply(lambda x : x* 2)
df.head()

,Sales _date,Category,Value,Product,Sales,Region,Sales_fillNA,New_Value,Value_New
0,2023-09-01,Clothing,343.0,Jacket,41873.29,North,41873.29,343,686.0
1,2023-04-26,Books,378.0,Headphones,24518.15,East,24518.15,378,756.0
2,NaN,Electronics,740.0,Jacket,44212.64,South,44212.64,740,1480.0
3,NaN,Food,469.0,Pizza,7143.52,North,7143.52,469,938.0
4,NaN,Clothing,546.0,Pizza,32402.12,South,32402.12,546,1092.0

In [60]:
## data  agreegating and grouping
df.head()

,Sales _date,Category,Value,Product,Sales,Region,Sales_fillNA,New_Value,Value_New
0,2023-09-01,Clothing,343.0,Jacket,41873.29,North,41873.29,343,686.0
1,2023-04-26,Books,378.0,Headphones,24518.15,East,24518.15,378,756.0
2,NaN,Electronics,740.0,Jacket,44212.64,South,44212.64,740,1480.0
3,NaN,Food,469.0,Pizza,7143.52,North,7143.52,469,938.0
4,NaN,Clothing,546.0,Pizza,32402.12,South,32402.12,546,1092.0

In [61]:
grouped_mean = df.groupby('Product')['Value'].mean()

In [62]:
grouped_mean

Product
Burger        299.428571
Comics        497.875000
Headphones    464.375000
Jacket        484.333333
Laptop        439.500000
Novel         336.000000
Pizza         424.000000
Shirt         611.500000
Name: Value, dtype: float64

In [63]:
grouped_sum = df.groupby(['Product', 'Region'])['Value'].sum()
grouped_sum

Product     Region
Burger      East      1154.0
            South       21.0
            West       921.0
Comics      East       625.0
            North      179.0
            South      440.0
            West       875.0
Headphones  East       826.0
            North       67.0
            South      683.0
            West      1175.0
Jacket      East         0.0
            North      343.0
            South      740.0
            West       370.0
Laptop      East       411.0
            North     1299.0
            South      972.0
            West       834.0
Novel       East       896.0
            North      131.0
            South      317.0
Pizza       East       257.0
            North      469.0
            South      546.0
Shirt       South      296.0
            West       927.0
Name: Value, dtype: float64

In [64]:
## Aggregatting function
grouped_agg = df.groupby('Region')['Value'].agg(['mean', 'sum', 'count'])
grouped_agg

              mean     sum  count
Region
East    379.000000  4169.0     11
North   351.250000  2810.0      8
South   401.500000  4015.0     10
West    470.583333  5647.0     12

In [67]:
## Merging and joining dataframe
df1 = pd.DataFrame({'Key' : ['A', 'B', 'C', 'D'], 'Value1' : [1, 2, 3, 4]})
df2 = pd.DataFrame({'Key' : ['A', 'B', 'C', 'E'], 'Value2' : [6, 7, 8, 9]})

In [68]:
df1

  Key  Value1
0   A       1
1   B       2
2   C       3
3   D       4

In [69]:
df2

  Key  Value2
0   A       6
1   B       7
2   C       8
3   E       9

In [70]:
pd.merge(df1, df2)

  Key  Value1  Value2
0   A       1       6
1   B       2       7
2   C       3       8

In [72]:
pd.merge(df1, df2, on = 'Key', how = 'inner')

  Key  Value1  Value2
0   A       1       6
1   B       2       7
2   C       3       8

In [73]:
pd.merge(df1, df2, on = 'Key', how = 'outer')

  Key  Value1  Value2
0   A     1.0     6.0
1   B     2.0     7.0
2   C     3.0     8.0
3   D     4.0     NaN
4   E     NaN     9.0

In [74]:
pd.merge(df1, df2, on = 'Key', how = 'left')

  Key  Value1  Value2
0   A       1     6.0
1   B       2     7.0
2   C       3     8.0
3   D       4     NaN

In [75]:
pd.merge(df1, df2, on = 'Key', how = 'right')

  Key  Value1  Value2
0   A     1.0       6
1   B     2.0       7
2   C     3.0       8
3   E     NaN       9

## Reading Data From Different sources

In [3]:
import pandas as pd 
from io import StringIO
Data = '{"Employee_name" : "James", "email" : "James@gmail.com", "job_profile" : [{"Title1" : "Team Lead" , "Tittle2" : "Senoir Devoloper"}]}' 
df = pd.read_json(StringIO(Data))

In [80]:
df

,Employee_name,email,job_profile
0,James,James@gmail.com,"{'Title1': 'Team Lead', 'Tittle2': 'Senoir Dev..."

In [81]:
df.to_json()

'{"Employee_name":{"0":"James"},"email":{"0":"James@gmail.com"},"job_profile":{"0":{"Title1":"Team Lead","Tittle2":"Senoir Devoloper"}}}'

In [4]:
df.to_json(orient='index')

'{"0":{"Employee_name":"James","email":"James@gmail.com","job_profile":{"Title1":"Team Lead","Tittle2":"Senoir Devoloper"}}}'

In [5]:
df.to_json(orient='records')

'[{"Employee_name":"James","email":"James@gmail.com","job_profile":{"Title1":"Team Lead","Tittle2":"Senoir Devoloper"}}]'

In [10]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data"
df = pd.read_csv(url, header=None)

In [11]:
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735

In [12]:
df.to_csv('wine.csv')

In [13]:
!pip install lxml

Collecting lxml
  Downloading lxml-6.0.0-cp313-cp313-macosx_10_13_universal2.whl.metadata (6.6 kB)
Downloading lxml-6.0.0-cp313-cp313-macosx_10_13_universal2.whl (8.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.4/8.4 MB 5.2 MB/s  0:00:01m0:00:0100:01
Installing collected packages: lxml
Successfully installed lxml-6.0.0

In [15]:
!pip install html5lib

Collecting html5lib
  Downloading html5lib-1.1-py2.py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: six>=1.9 in /Users/abdulqadir0210423gmail.com/.pyenv/versions/3.13.5/lib/python3.13/site-packages (from html5lib) (1.17.0)
Collecting webencodings (from html5lib)
  Using cached webencodings-0.5.1-py2.py3-none-any.whl.metadata (2.1 kB)
Downloading html5lib-1.1-py2.py3-none-any.whl (112 kB)
Using cached webencodings-0.5.1-py2.py3-none-any.whl (11 kB)
Installing collected packages: webencodings, html5lib
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [html5lib]
Successfully installed html5lib-1.1 webencodings-0.5.1

In [16]:
!pip install beautifulsoup4

Collecting beautifulsoup4
  Using cached beautifulsoup4-4.13.4-py3-none-any.whl.metadata (3.8 kB)
Collecting soupsieve>1.2 (from beautifulsoup4)
  Using cached soupsieve-2.7-py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: typing-extensions>=4.0.0 in /Users/abdulqadir0210423gmail.com/.pyenv/versions/3.13.5/lib/python3.13/site-packages (from beautifulsoup4) (4.14.1)
Using cached beautifulsoup4-4.13.4-py3-none-any.whl (187 kB)
Using cached soupsieve-2.7-py3-none-any.whl (36 kB)
Installing collected packages: soupsieve, beautifulsoup4
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [beautifulsoup4]
Successfully installed beautifulsoup4-4.13.4 soupsieve-2.7

In [17]:
url = "https://www.fdic.gov/resources/resolutions/bank-failures/failed-bank-list/"
df = pd.read_html(url)

In [18]:
df

[                                            Bank Name                City  \
 0                        The Santa Anna National Bank          Santa Anna
 1                                Pulaski Savings Bank             Chicago
 2                  The First National Bank of Lindsay             Lindsay
 3               Republic First Bank dba Republic Bank        Philadelphia
 4                                       Citizens Bank            Sac City
 5                            Heartland Tri-State Bank             Elkhart
 6                                 First Republic Bank       San Francisco
 7                                      Signature Bank            New York
 8                                 Silicon Valley Bank         Santa Clara
 9                                   Almena State Bank              Almena
 10                         First City Bank of Florida   Fort Walton Beach
 11                               The First State Bank       Barboursville
 12                                 Ericson State Bank             Ericson
 13                   City National Bank of New Jersey              Newark
 14                                      Resolute Bank              Maumee
 15                              Louisa Community Bank              Louisa
 16                               The Enloe State Bank              Cooper
 17                Washington Federal Bank for Savings             Chicago
 18    The Farmers and Merchants State Bank of Argonia             Argonia
 19                                Fayette County Bank          Saint Elmo
 20  Guaranty Bank, (d/b/a BestBank in Georgia & Mi...           Milwaukee
 21                                     First NBC Bank         New Orleans
 22                                      Proficio Bank  Cottonwood Heights
 23                      Seaway Bank and Trust Company             Chicago
 24                             Harvest Community Bank          Pennsville

             State   Cert                Acquiring Institution  \
 0           Texas   5520            Coleman County State Bank
 1        Illinois  28611                      Millennium Bank
 2        Oklahoma   4134               First Bank & Trust Co.
 3    Pennsylvania  27332    Fulton Bank, National Association
 4            Iowa   8758            Iowa Trust & Savings Bank
 5          Kansas  25851               Dream First Bank, N.A.
 6      California  59017            JPMorgan Chase Bank, N.A.
 7        New York  57053                  Flagstar Bank, N.A.
 8      California  24735  First Citizens Bank & Trust Company
 9          Kansas  15426                          Equity Bank
 10        Florida  16748            United Fidelity Bank, fsb
 11  West Virginia  14361                       MVB Bank, Inc.
 12       Nebraska  18265           Farmers and Merchants Bank
 13     New Jersey  21111                      Industrial Bank
 14           Ohio  58317                   Buckeye State Bank
 15       Kentucky  58112    Kentucky Farmers Bank Corporation
 16          Texas  10716                   Legend Bank, N. A.
 17       Illinois  30570                   Royal Savings Bank
 18         Kansas  17719                          Conway Bank
 19       Illinois   1802            United Fidelity Bank, fsb
 20      Wisconsin  30003  First-Citizens Bank & Trust Company
 21      Louisiana  58302                         Whitney Bank
 22           Utah  35495                    Cache Valley Bank
 23       Illinois  19328                  State Bank of Texas
 24     New Jersey  34951  First-Citizens Bank & Trust Company

          Closing Date  Fund  Sort ascending
 0       June 27, 2025                 10549
 1    January 17, 2025                 10548
 2    October 18, 2024                 10547
 3      April 26, 2024                 10546
 4    November 3, 2023                 10545
 5       July 28, 2023                 10544
 6         May 1, 2023                 10543
 7      March 12, 2023                 10540
 8      March 10, 2023                 10539
 9    October 23, 2020                 10538
 10   October 16, 2020                 10537
 11      April 3, 2020                 10536
 12  February 14, 2020                 10535
 13   November 1, 2019                 10534
 14   October 25, 2019                 10533
 15   October 25, 2019                 10532
 16       May 31, 2019                 10531
 17  December 15, 2017                 10530
 18   October 13, 2017                 10529
 19       May 26, 2017                 10528
 20        May 5, 2017                 10527
 21     April 28, 2017                 10526
 22      March 3, 2017                 10525
 23   January 27, 2017                 10524
 24   January 13, 2017                 10523  ]

In [19]:
df[0]

,Bank Name,City,State,Cert,Acquiring Institution,Closing Date,Fund Sort ascending
0,The Santa Anna National Bank,Santa Anna,Texas,5520,Coleman County State Bank,"June 27, 2025",10549
1,Pulaski Savings Bank,Chicago,Illinois,28611,Millennium Bank,"January 17, 2025",10548
2,The First National Bank of Lindsay,Lindsay,Oklahoma,4134,First Bank & Trust Co.,"October 18, 2024",10547
3,Republic First Bank dba Republic Bank,Philadelphia,Pennsylvania,27332,"Fulton Bank, National Association","April 26, 2024",10546
4,Citizens Bank,Sac City,Iowa,8758,Iowa Trust & Savings Bank,"November 3, 2023",10545
5,Heartland Tri-State Bank,Elkhart,Kansas,25851,"Dream First Bank, N.A.","July 28, 2023",10544
6,First Republic Bank,San Francisco,California,59017,"JPMorgan Chase Bank, N.A.","May 1, 2023",10543
7,Signature Bank,New York,New York,57053,"Flagstar Bank, N.A.","March 12, 2023",10540
8,Silicon Valley Bank,Santa Clara,California,24735,First Citizens Bank & Trust Company,"March 10, 2023",10539
9,Almena State Bank,Almena,Kansas,15426,Equity Bank,"October 23, 2020",10538
10,First City Bank of Florida,Fort Walton Beach,Florida,16748,"United Fidelity Bank, fsb","October 16, 2020",10537
11,The First State Bank,Barboursville,West Virginia,14361,"MVB Bank, Inc.","April 3, 2020",10536
12,Ericson State Bank,Ericson,Nebraska,18265,Farmers and Merchants Bank,"February 14, 2020",10535
13,City National Bank of New Jersey,Newark,New Jersey,21111,Industrial Bank,"November 1, 2019",10534
14,Resolute Bank,Maumee,Ohio,58317,Buckeye State Bank,"October 25, 2019",10533
15,Louisa Community Bank,Louisa,Kentucky,58112,Kentucky Farmers Bank Corporation,"October 25, 2019",10532
16,The Enloe State Bank,Cooper,Texas,10716,"Legend Bank, N. A.","May 31, 2019",10531
17,Washington Federal Bank for Savings,Chicago,Illinois,30570,Royal Savings Bank,"December 15, 2017",10530
18,The Farmers and Merchants State Bank of Argonia,Argonia,Kansas,17719,Conway Bank,"October 13, 2017",10529
19,Fayette County Bank,Saint Elmo,Illinois,1802,"United Fidelity Bank, fsb","May 26, 2017",10528
20,"Guaranty Bank, (d/b/a BestBank in Georgia & Mi...",Milwaukee,Wisconsin,30003,First-Citizens Bank & Trust Company,"May 5, 2017",10527
21,First NBC Bank,New Orleans,Louisiana,58302,Whitney Bank,"April 28, 2017",10526
22,Proficio Bank,Cottonwood Heights,Utah,35495,Cache Valley Bank,"March 3, 2017",10525
23,Seaway Bank and Trust Company,Chicago,Illinois,19328,State Bank of Texas,"January 27, 2017",10524
24,Harvest Community Bank,Pennsville,New Jersey,34951,First-Citizens Bank & Trust Company,"January 13, 2017",10523

In [20]:
url = "https://en.wikipedia.org/wiki/Mobile_country_code"
df = pd.read_html(url,match = "Country", header=0)

In [21]:
df

[     Mobile country code                                    Country ISO 3166  \
 0                    289                                 A Abkhazia    GE-AB
 1                    412                                Afghanistan       AF
 2                    276                                    Albania       AL
 3                    603                                    Algeria       DZ
 4                    544  American Samoa (United States of America)       AS
 ..                   ...                                        ...      ...
 247                  452                                    Vietnam       VN
 248                  543                        W Wallis and Futuna       WF
 249                  421                                    Y Yemen       YE
 250                  645                                   Z Zambia       ZM
 251                  648                                   Zimbabwe       ZW

                                   Mobile network codes National MNC authority  \
 0             List of mobile network codes in Abkhazia                    NaN
 1          List of mobile network codes in Afghanistan                    NaN
 2              List of mobile network codes in Albania                    NaN
 3              List of mobile network codes in Algeria                    NaN
 4       List of mobile network codes in American Samoa                    NaN
 ..                                                 ...                    ...
 247        List of mobile network codes in the Vietnam                    NaN
 248  List of mobile network codes in Wallis and Futuna                    NaN
 249          List of mobile network codes in the Yemen                    NaN
 250             List of mobile network codes in Zambia                    NaN
 251           List of mobile network codes in Zimbabwe                    NaN

                       Remarks
 0    MCC is not listed by ITU
 1                         NaN
 2                         NaN
 3                         NaN
 4                         NaN
 ..                        ...
 247                       NaN
 248                       NaN
 249                       NaN
 250                       NaN
 251                       NaN

 [252 rows x 6 columns]]

In [22]:
df[0]

,Mobile country code,Country,ISO 3166,Mobile network codes,National MNC authority,Remarks
0,289,A Abkhazia,GE-AB,List of mobile network codes in Abkhazia,NaN,MCC is not listed by ITU
1,412,Afghanistan,AF,List of mobile network codes in Afghanistan,NaN,NaN
2,276,Albania,AL,List of mobile network codes in Albania,NaN,NaN
3,603,Algeria,DZ,List of mobile network codes in Algeria,NaN,NaN
4,544,American Samoa (United States of America),AS,List of mobile network codes in American Samoa,NaN,NaN
...,...,...,...,...,...,...
247,452,Vietnam,VN,List of mobile network codes in the Vietnam,NaN,NaN
248,543,W Wallis and Futuna,WF,List of mobile network codes in Wallis and Futuna,NaN,NaN
249,421,Y Yemen,YE,List of mobile network codes in the Yemen,NaN,NaN
250,645,Z Zambia,ZM,List of mobile network codes in Zambia,NaN,NaN
251,648,Zimbabwe,ZW,List of mobile network codes in Zimbabwe,NaN,NaN

In [24]:
!pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [openpyxl]1/2 [openpyxl]
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

In [25]:
pd.read_excel('data.xlsx')

          Name  Age
0  Abdul Qadir   24
1          xyz   31

In [27]:
df_excel = pd.read_excel('data.xlsx')

In [31]:
df_excel.to_pickle("df_excel.pkl")

In [32]:
pd.read_pickle('df_excel.pkl')

          Name  Age
0  Abdul Qadir   24
1          xyz   31